#!/bin/zsh

function import {
    local dotfiles_base_dir
    dotfiles_base_dir="$(dirname "${0:A}")"

    # shellcheck disable=SC1090
    source "$dotfiles_base_dir/$1"
}

function warning {
    printf "The following files will be irreversibly modified:\n"

    for file in "$@"; do
        printf "  * %s\n" "$file"
    done

    printf "\n"
    printf "Do you want to proceed? [type 'YES' to accept]: "
    read -r

    if [[ $REPLY != "YES" ]]; then
        return 1
    fi

    return 0
}

function install_extension {
    local ext_path="$1"
    local out_file="$2"

    local ext_name
    ext_name="$(basename "$extension_path")"

    # shellcheck disable=SC1090
    source "$ext_path/extension.zsh"
    extension::"$ext_name"

    local output
    output="$(cat "$extension_path/template.zsh")"

    printf "\n%s\n%s\n%s\n" "# Extension '$ext_name'" "$output" "# End '$ext_name'" >> "$out_file"
}

function install {
    local dotfiles_base_dir="$1"
    shift

    local autoloads=("$@")

    cp "$dotfiles_base_dir/zshrc/base.zsh" ~/.zshrc
    cp "$dotfiles_base_dir/config/vimrc" ~/.vimrc

    if ssh::has_config; then
        cp "$dotfiles_base_dir/config/sshconfig" ~/.ssh/config
    fi

    for autoload in "${autoloads[@]}"; do
        printf "autoload -Uz %s\n" "$autoload" >> ~/.zshrc
    done

    for extension_path in $(ls_ext "$dotfiles_base_dir" --with-paths); do
        install_extension "$extension_path" ~/.zshrc
    done
}

function main {
    local script_path="${0:A}"
    local dotfiles_base_dir
    dotfiles_base_dir="$(dirname "$script_path")"

    local autoloads=()

    local modifies=(
        "$HOME/.zshrc"
        "$HOME/.vimrc"
    )

    if ssh::has_config; then
        modifies+=("$HOME/.ssh/config")
    fi

    for extension in $(ls_ext "$dotfiles_base_dir" --with-paths); do
        . "$extension"/extension.zsh

        modifies=("${modifies[@]}" "${MODIFIES[@]}")
        unset MODIFIES

        autoloads=("${autoloads[@]}" "${AUTOLOADS[@]}")
        unset AUTOLOADS
    done

    # remove duplicates.
    # We disable shellcheck here, because while the highlighted issue is valid,
    # other solutions are unnecessarily bulky.
    #
    # shellcheck disable=SC2207
    autoloads=($(printf "%s\n" "${autoloads[@]}" | sort -u))

    if ! warning "${modifies[@]}"; then
        printf "Quitting... your existing configuration has been left untouched.\n"
        exit
    fi

    install "$dotfiles_base_dir" "${autoloads[@]}"
}

import lib/ssh.zsh
import lib/extension.zsh

main "$@"

unset import
unset warning
unset install_extension
unset install
unset main