#!/bin/zsh

function warning {
    printf "The following files will be irreversibly modified:\n"

    for file in "$@"; do
        printf "  * %s\n" "$file"
    done

    printf "\n"
    printf "Do you want to proceed? [type 'YES' to accept]: "
    read -r

    if [[ $REPLY != "YES" ]]; then
        return 1
    fi

    return 0
}

function install_extension {
    local ext_path
    ext_path=$1

    local ext_name
    ext_name="$(basename "$extension_path" | cut -d '.' -f 1)"

    # shellcheck disable=SC1090
    source "$ext_path"

    local output
    output="$(extension_"$ext_name")"

    printf "%s\n%s\n%s\n" "# Extension '$ext_name'" "$output" "# End '$ext_name'" >> ~/.zshrc
}

function install {
    local dotfiles_base_dir="$1"

    cp "$dotfiles_base_dir/config/zshrc" ~/.zshrc
    cp "$dotfiles_base_dir/config/vimrc" ~/.vimrc

    printf "\n\n# Dynamic Extensions\n\n" >> ~/.zshrc

    for extension_path in "$dotfiles_base_dir"/extensions/*; do
        install_extension "$extension_path"
    done
}

function main {
    local script_path="${0:A}"

    local modifies=(
        "$HOME/.zshrc"
        "$HOME/.vimrc"
    )

    if ! warning "${modifies[@]}"; then
        printf "Quitting... your existing configuration has been left untouched.\n"
        exit
    fi

    install "$(dirname "$script_path")"
}

main "$@"

unset warning
unset install_extension
unset install
unset main