autoload -Uz compinit
autoload -Uz vcs_info

compinit

# Prompt string configuration

function precmd {
    vcs_info
}

function setps {
    PS1='%F{%(?.green.red)}%1~%f %B›%b '
    RPS1="%F{red}${vcs_info_msg_0_}%f"
}

zstyle ':vcs_info:git:*' formats '%b'
setopt PROMPT_SUBST

precmd_functions+=(setps)

# Tab-Completion configuration

zstyle ':completion:*:options' list-colors '=(#b)*(-- *)=1;38;5;13=38;5;45' '=*=1;38;5;13'
zstyle ':completion:*' use-compctl false
zstyle ':compinstall' filename "$HOME/.zshrc"

# Vi-Mode

bindkey -v

KEYTIMEOUT=5

function zle-keymap-select {
    if [[ $KEYMAP == "vicmd" ]]; then
        printf '\e[3 q' # underscore
    fi

    if [[ $KEYMAP == "main" || $KEYMAP == "viins" ]]; then
        printf '\e[5 q' # beam
    fi
}

zle -N zle-keymap-select

printf '\e[5 q' # default mode is INSERT
